name: Deploy to NearlyFreeSpeech

on: [push]

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code # Checkout the latest code
        uses: actions/checkout@v3

      - name: 📂 SFTP uploader # Upload to SFTP
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ secrets.NFSN_HOSTNAME }}
          username: ${{ secrets.NFSN_USERNAME }}
          password: ${{ secrets.NFSN_PASSWORD }}
          forceUpload: true
          localDir: "/public"
          remoteDir: "/" 
